# Generated by Django 5.0.3 on 2024-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
